language: java
sudo: false
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"

script: "./mvnw clean install -Prun-its"

branches:
  only:
  - master
